---
title: FEWD
url: http://siteleaf_fewd.nevan.org
timezone: UTC
collections:
  _homework:
    title: Homework
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
